"""WebSocket client for portal-to-agent communication.

Connects out to the Wright portal WebSocket endpoint and listens for
commands (e.g. start/stop fan detection).  Events generated by the
scheduler are forwarded to the portal over the same connection.
"""

from __future__ import annotations

import asyncio
import json
import logging
import queue
import threading
from typing import Any, Optional

logger = logging.getLogger(__name__)

_MAX_BACKOFF = 300  # 5 minutes
_EVENT_POLL_INTERVAL = 0.1  # seconds


class AgentController:
    """Thread-safe shared state between the WebSocket client and the scheduler."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._mode = "normal"
        self._mode_changed = threading.Event()
        self._event_queue: queue.Queue[dict[str, Any]] = queue.Queue()

    @property
    def mode(self) -> str:
        with self._lock:
            return self._mode

    def request_fan_detection(self) -> None:
        with self._lock:
            self._mode = "fan_detection"
        self._mode_changed.set()

    def request_normal(self) -> None:
        with self._lock:
            self._mode = "normal"
        self._mode_changed.set()

    def wait_for_mode_change(self, timeout: Optional[float] = None) -> bool:
        """Block until the mode changes or *timeout* elapses.

        Returns ``True`` if the mode changed, ``False`` on timeout.
        """
        result = self._mode_changed.wait(timeout=timeout)
        self._mode_changed.clear()
        return result

    def push_event(self, event: dict[str, Any]) -> None:
        self._event_queue.put_nowait(event)

    def pop_events(self) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []
        while True:
            try:
                events.append(self._event_queue.get_nowait())
            except queue.Empty:
                break
        return events


class WebSocketClient:
    """Maintains a persistent WebSocket connection to the Wright portal.

    Runs in a daemon thread with its own asyncio event loop.
    """

    def __init__(
        self,
        controller: AgentController,
        api_url: str,
        api_key: str,
        facility_id: str,
    ) -> None:
        self.controller = controller
        self.api_key = api_key
        self.facility_id = facility_id
        self._ws_url = self._build_ws_url(api_url)
        self._thread: Optional[threading.Thread] = None

    @staticmethod
    def _build_ws_url(api_url: str) -> str:
        url = api_url.rstrip("/")
        if url.startswith("https://"):
            url = "wss://" + url[len("https://"):]
        elif url.startswith("http://"):
            url = "ws://" + url[len("http://"):]
        return f"{url}/api/v1/ws/agent"

    # ------------------------------------------------------------------
    # Async internals
    # ------------------------------------------------------------------

    async def _send_json(self, ws: Any, data: dict[str, Any]) -> None:
        await ws.send(json.dumps(data))

    async def _event_forwarder(self, ws: Any) -> None:
        """Drain the controller event queue and send to the portal."""
        while True:
            events = self.controller.pop_events()
            for event in events:
                try:
                    await self._send_json(ws, event)
                except Exception:
                    return
            await asyncio.sleep(_EVENT_POLL_INTERVAL)

    async def _message_handler(self, ws: Any) -> None:
        """Listen for commands from the portal."""
        async for raw in ws:
            try:
                msg = json.loads(raw)
            except (json.JSONDecodeError, TypeError):
                logger.warning("Invalid JSON from portal: %s", raw)
                continue

            command = msg.get("command")
            if command == "start_fan_detection":
                logger.info("Portal requested fan detection mode")
                self.controller.request_fan_detection()
            elif command == "stop_fan_detection":
                logger.info("Portal requested normal mode")
                self.controller.request_normal()
            else:
                logger.debug("Unknown portal command: %s", command)

    async def _connect_loop(self) -> None:
        import websockets

        consecutive_failures = 0

        while True:
            try:
                logger.info("Connecting to portal WebSocket: %s", self._ws_url)
                async with websockets.connect(self._ws_url) as ws:
                    await self._send_json(ws, {
                        "api_key": self.api_key,
                        "facility_id": self.facility_id,
                    })

                    response = await asyncio.wait_for(ws.recv(), timeout=10)
                    resp = json.loads(response)
                    if resp.get("error"):
                        logger.error("Portal auth failed: %s", resp["error"])
                        await asyncio.sleep(30)
                        continue

                    logger.info("Connected to portal WebSocket")
                    consecutive_failures = 0

                    forwarder = asyncio.create_task(self._event_forwarder(ws))
                    try:
                        await self._message_handler(ws)
                    finally:
                        forwarder.cancel()

            except asyncio.CancelledError:
                break
            except Exception as exc:
                consecutive_failures += 1
                backoff = min(5 * (2 ** (consecutive_failures - 1)), _MAX_BACKOFF)
                logger.warning(
                    "WebSocket connection failed (attempt #%d): %s. Retrying in %ds...",
                    consecutive_failures, exc, backoff,
                )
                await asyncio.sleep(backoff)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Start the WebSocket client in a background daemon thread."""
        def _run() -> None:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            loop.run_until_complete(self._connect_loop())

        self._thread = threading.Thread(target=_run, daemon=True)
        self._thread.start()
        logger.info("WebSocket client started (target: %s)", self._ws_url)
