"""WebSocket client for portal-to-agent communication.

Connects out to the Wright portal WebSocket endpoint and listens for
commands (e.g. start/stop fan detection).  Events generated by the
scheduler are forwarded to the portal over the same connection.
"""

from __future__ import annotations

import asyncio
import json
import logging
import queue
import ssl
import threading
from typing import Any, Optional

from wright_telemetry.api_client import wright_api_v1_url
from wright_telemetry.config import load_config, save_config, mask_config

logger = logging.getLogger(__name__)

_MAX_BACKOFF = 300  # 5 minutes
_EVENT_POLL_INTERVAL = 0.1  # seconds


class AgentController:
    """Thread-safe shared state between the WebSocket client and the scheduler."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._mode = "normal"
        self._mode_changed = threading.Event()
        self._config_reload = threading.Event()
        self._event_queue: queue.Queue[dict[str, Any]] = queue.Queue()

    @property
    def mode(self) -> str:
        with self._lock:
            return self._mode

    def request_fan_detection(self) -> None:
        with self._lock:
            self._mode = "fan_detection"
        self._mode_changed.set()

    def request_normal(self) -> None:
        with self._lock:
            self._mode = "normal"
        self._mode_changed.set()

    def wait_for_mode_change(self, timeout: Optional[float] = None) -> bool:
        """Block until the mode changes or *timeout* elapses.

        Returns ``True`` if the mode changed, ``False`` on timeout.
        """
        result = self._mode_changed.wait(timeout=timeout)
        self._mode_changed.clear()
        return result

    def push_event(self, event: dict[str, Any]) -> None:
        self._event_queue.put_nowait(event)

    def pop_events(self) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []
        while True:
            try:
                events.append(self._event_queue.get_nowait())
            except queue.Empty:
                break
        return events

    def request_config_reload(self) -> None:
        """Signal the scheduler to reload config from disk."""
        self._config_reload.set()

    def check_config_reload(self) -> bool:
        """Return True if a config reload was requested, clearing the flag."""
        triggered = self._config_reload.is_set()
        self._config_reload.clear()
        return triggered


class WebSocketClient:
    """Maintains a persistent WebSocket connection to the Wright portal.

    Runs in a daemon thread with its own asyncio event loop.
    """

    def __init__(
        self,
        controller: AgentController,
        api_url: str,
        api_key: str,
        facility_id: str,
    ) -> None:
        self.controller = controller
        self.api_key = api_key
        self.facility_id = facility_id
        self._ws_url = self._build_ws_url(api_url)
        self._thread: Optional[threading.Thread] = None

    @staticmethod
    def _build_ws_url(api_url: str) -> str:
        """Map HTTP API base to ``ws(s)://`` ``/api/v1/ws/agent``."""
        http_url = wright_api_v1_url(api_url, "ws", "agent")
        if http_url.startswith("https://"):
            return "wss://" + http_url[len("https://"):]
        if http_url.startswith("http://"):
            return "ws://" + http_url[len("http://"):]
        return http_url

    # ------------------------------------------------------------------
    # Async internals
    # ------------------------------------------------------------------

    async def _send_json(self, ws: Any, data: dict[str, Any]) -> None:
        await ws.send(json.dumps(data))

    async def _event_forwarder(self, ws: Any) -> None:
        """Drain the controller event queue and send to the portal."""
        while True:
            events = self.controller.pop_events()
            for event in events:
                try:
                    await self._send_json(ws, event)
                except Exception:
                    return
            await asyncio.sleep(_EVENT_POLL_INTERVAL)

    async def _message_handler(self, ws: Any) -> None:
        """Listen for commands from the portal."""
        async for raw in ws:
            try:
                msg = json.loads(raw)
            except (json.JSONDecodeError, TypeError):
                logger.warning("Invalid JSON from portal: %s", raw)
                continue

            command = msg.get("command")
            if command == "start_fan_detection":
                logger.info("Portal requested fan detection mode")
                self.controller.request_fan_detection()
            elif command == "stop_fan_detection":
                logger.info("Portal requested normal mode")
                self.controller.request_normal()
            elif command in ("get_config", "update_config"):
                self._handle_config_command(command, msg)
            else:
                logger.debug("Unknown portal command: %s", command)

    def _handle_config_command(self, command: str, msg: dict[str, Any]) -> None:
        """Handle get_config / update_config commands with consent check."""
        cfg = load_config()
        if cfg is None:
            self.controller.push_event({
                "event": "config_error",
                "error": "No configuration file found on this agent.",
            })
            return

        consent = cfg.get("consent", {})
        if not consent.get("remote_config", False):
            self.controller.push_event({
                "event": "config_error",
                "error": (
                    "Remote configuration is not enabled on this agent. "
                    "Run 'wright-telemetry --setup' on the agent machine "
                    "and enable the 'Remote Configuration' option."
                ),
            })
            return

        if command == "get_config":
            self.controller.push_event({
                "event": "config_response",
                "config": mask_config(cfg),
            })
        elif command == "update_config":
            payload = msg.get("payload")
            if not isinstance(payload, dict) or not payload:
                self.controller.push_event({
                    "event": "config_error",
                    "error": "update_config requires a non-empty 'payload' object.",
                })
                return
            try:
                self._apply_config_update(cfg, payload)
            except Exception as exc:
                logger.exception("Failed to apply config update")
                self.controller.push_event({
                    "event": "config_error",
                    "error": f"Failed to update configuration: {exc}",
                })

    def _apply_config_update(self, cfg: dict[str, Any], payload: dict[str, Any]) -> None:
        """Validate, merge, save, and emit updated config."""
        VALID_COLLECTOR_TYPES = ("braiins", "luxos", "vnish")

        if "poll_interval_seconds" in payload:
            val = payload["poll_interval_seconds"]
            if not isinstance(val, (int, float)) or val < 1:
                self.controller.push_event({
                    "event": "config_error",
                    "error": "poll_interval_seconds must be a positive number.",
                })
                return

        if "collector_type" in payload:
            val = payload["collector_type"]
            if val not in VALID_COLLECTOR_TYPES:
                self.controller.push_event({
                    "event": "config_error",
                    "error": f"collector_type must be one of: {', '.join(VALID_COLLECTOR_TYPES)}",
                })
                return

        if "update_check_interval" in payload:
            val = payload["update_check_interval"]
            if not isinstance(val, (int, float)) or val < 10:
                self.controller.push_event({
                    "event": "config_error",
                    "error": "update_check_interval must be at least 10 seconds.",
                })
                return

        if "fan_detection_idle_timeout" in payload:
            val = payload["fan_detection_idle_timeout"]
            if not isinstance(val, (int, float)) or val < 60:
                self.controller.push_event({
                    "event": "config_error",
                    "error": "fan_detection_idle_timeout must be at least 60 seconds.",
                })
                return

        FORBIDDEN_KEYS = ("wright_api_key",)
        for key in FORBIDDEN_KEYS:
            if key in payload:
                self.controller.push_event({
                    "event": "config_error",
                    "error": f"'{key}' cannot be changed remotely for security reasons.",
                })
                return

        SCALAR_KEYS = (
            "poll_interval_seconds", "collector_type", "wright_api_url",
            "facility_id", "disable_auto_update", "update_check_interval",
            "fan_detection_idle_timeout",
        )
        for key in SCALAR_KEYS:
            if key in payload:
                cfg[key] = payload[key]

        if "discovery" in payload and isinstance(payload["discovery"], dict):
            disc = cfg.get("discovery", {})
            disc.update(payload["discovery"])
            cfg["discovery"] = disc

        if "consent" in payload and isinstance(payload["consent"], dict):
            cons = cfg.get("consent", {})
            cons.update(payload["consent"])
            cfg["consent"] = cons

        if "miners" in payload and isinstance(payload["miners"], list):
            cfg["miners"] = payload["miners"]

        save_config(cfg)
        logger.info("Configuration updated remotely and saved to disk")
        self.controller.request_config_reload()
        self.controller.push_event({
            "event": "config_updated",
            "success": True,
            "config": mask_config(cfg),
        })

    async def _connect_loop(self) -> None:
        import websockets

        consecutive_failures = 0
        # TODO: Re-enable TLS verification before shipping production builds.
        connect_kw: dict[str, Any] = {}
        if self._ws_url.startswith("wss://"):
            _ctx = ssl.create_default_context()
            _ctx.check_hostname = False
            _ctx.verify_mode = ssl.CERT_NONE
            connect_kw["ssl"] = _ctx

        while True:
            try:
                logger.info("Connecting to portal WebSocket: %s", self._ws_url)
                async with websockets.connect(self._ws_url, **connect_kw) as ws:
                    await self._send_json(ws, {
                        "api_key": self.api_key,
                        "facility_id": self.facility_id,
                    })

                    response = await asyncio.wait_for(ws.recv(), timeout=10)
                    resp = json.loads(response)
                    if resp.get("error"):
                        logger.error("Portal auth failed: %s", resp["error"])
                        await asyncio.sleep(30)
                        continue

                    logger.info("Connected to portal WebSocket")
                    consecutive_failures = 0

                    forwarder = asyncio.create_task(self._event_forwarder(ws))
                    try:
                        await self._message_handler(ws)
                    finally:
                        forwarder.cancel()
                        if self.controller.mode != "normal":
                            logger.info(
                                "Connection lost while in '%s' mode — reverting to normal",
                                self.controller.mode,
                            )
                            self.controller.request_normal()

            except asyncio.CancelledError:
                break
            except Exception as exc:
                consecutive_failures += 1
                backoff = min(5 * (2 ** (consecutive_failures - 1)), _MAX_BACKOFF)
                logger.warning(
                    "WebSocket connection failed (attempt #%d): %s. Retrying in %ds...",
                    consecutive_failures, exc, backoff,
                )
                await asyncio.sleep(backoff)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Start the WebSocket client in a background daemon thread."""
        def _run() -> None:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            loop.run_until_complete(self._connect_loop())

        self._thread = threading.Thread(target=_run, daemon=True)
        self._thread.start()
        logger.info("WebSocket client started (target: %s)", self._ws_url)
