; Inno Setup script for WrightData (Windows installer)
; Generated by build_windows.bat — do not hand-edit the version line.
;
; Requires Inno Setup 6+: https://jrsoftware.org/isdl.php
; Build with:  iscc installer\inno_setup.iss  (from repo root)
; Or let build_windows.bat call iscc automatically.

#define MyAppName      "WrightData"
#define MyAppPublisher "Wright One"
#define MyAppURL       "https://wrightone.io"
#define MyAppExeName   "wright-telemetry-gui.exe"
; Version is injected by build_windows.bat via /DMyAppVersion=x.y.z
#ifndef MyAppVersion
  #define MyAppVersion "0.0.0"
#endif

[Setup]
AppId={{A3F1E2D4-7B8C-4F0A-9E5D-2C6B1A0F3E8D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Install into Program Files by default; falls back gracefully for non-admin
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Produce a single-file installer EXE in dist\ (relative to repo root, not this .iss file)
OutputDir={#SourcePath}\..\dist
OutputBaseFilename=WrightData-Windows
SetupIconFile={#SourcePath}\..\assets\wright-telemetry.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
; Minimum Windows version: Windows 10
MinVersion=10.0
PrivilegesRequiredOverridesAllowed=dialog
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon";    Description: "{cm:CreateDesktopIcon}";    GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startmenuicon";  Description: "Create a Start Menu shortcut"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
; The entire PyInstaller output directory
Source: "{#SourcePath}\..\dist\wright-telemetry-gui\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; CLI binary (single-file EXE)
Source: "{#SourcePath}\..\dist\wright-telemetry.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}";          Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}";  Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove any .pyc caches that PyInstaller drops at runtime
Type: filesandordirs; Name: "{app}\__pycache__"
